plugins {
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}" apply false
    id 'java'
}
group = 'org.ashlesha'
version = '1.0.0'
description = '(अश्लेषा) Ashlesha Group:- Strategic investment for transformative education.'

repositories {
    mavenCentral()
}


// ✅ Apply common config to all subprojects except root
subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(24)
        }
    }
    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        }
    }
    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    dependencies {
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }

    test {
        useJUnitPlatform()
    }
}