plugins {
    id 'application'
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '4.0.0-M2'
    id 'io.spring.dependency-management' version '1.1.7'
}

application {
    mainClass = 'org.ashlesha.Ashlesha'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation project(':users-service')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}
