plugins {
    id 'com.github.node-gradle.node' version '7.0.2'
}

node {
    download = true
    version = '20.11.1'
    npmVersion = '10.2.4'
    workDir = file("${project.buildDir}/nodejs")
    npmWorkDir = file("${project.buildDir}/npm")
}

import com.github.gradle.node.npm.task.NpmTask

tasks.register('npmInstall', NpmTask) {
    args = ['install']
}

tasks.register('npmBuild', NpmTask) {
    dependsOn tasks.named('npmInstall')
    args = ['run', 'build']
}

tasks.named('build') {
    dependsOn tasks.named('npmBuild')
}
